IvanIhnatsiuk/react-native-advanced-input-mask

.github/workflows/ci.yml, .gitignore, example/ios/.xcode.env.local, example/ios/Podfile.lock, example/package.json, yarn.lock
I updated react-native version to the 0.73.10 and removed .xcode.env.local file
iOS build job must be green 🙂 
- hermes-engine pod was updated to 0.75.2
tested on CI
=> Fix iOS build on CI

.github/workflows/build-android.yml, .github/workflows/build-ios.yml, .github/workflows/build-library.yml, .github/workflows/ci.yml, .github/workflows/lint.yml, .github/workflows/tests.yml
This pull request refactors the GitHub Actions workflows by modularizing the workflow definitions and reusing them across different jobs. The main changes include creating separate workflow files for building Android, iOS, and the library, as well as for linting and running tests. Additionally, the main CI workflow has been updated to reference these new modular workflows.
* Created a new workflow file for building Android applications (`.github/workflows/build-android.yml`).
* Created a new workflow file for building iOS applications (`.github/workflows/build-ios.yml`).
* Created a new workflow file for building the library (`.github/workflows/build-library.yml`).
* Created a new workflow file for linting files (`.github/workflows/lint.yml`).
* Created a new workflow file for running …
=> feat: split CI jobs

.github/workflows/build-ios.yml, android/src/main/java/com/maskedtextinput/managers/MaskedTextInputDecoratorViewManager.kt, example/ios/Podfile.lock, example/src/App.tsx, ios/MaskedTextInput.swift, ios/MaskedTextInputManager.mm, src/index.tsx, src/types.ts
These changes are addressed by changing the event name to onAdvancedMaskTextChange because of conflicts with the onChangeText event name from the react-native core.
=> fix: change text event name

example/src/App.tsx, ios/AdvancedTextInputMaskDecoratorView.swift, ios/AdvancedtextInputMaskDecoratorView.mm, package.json, src/index.tsx, src/specs/AdvancedTextInputMaskDecoratorViewNativeComponent.ts, src/types.ts
Added tail placeholder change event to have a complete list of mask features
tested on iOS simulator
tested on Android emulator
=> feat: add tail placeholder change event

example/src/App.tsx, src/index.tsx, src/types.ts
Aligned methods with react-native-text-input-mask to make it easier to migrate projects from react-native-text-input-mask to this library
- primaryMaskFormat to mask
- onAdvancedMaskTextChange -> onChangeText
tested on iOS and Android
https://github.com/user-attachments/assets/4eb36442-60ea-4abf-87e6-d27d39de890d
=> fix: align methods with react-native-text-input-mask

example/ios/Podfile.lock, package.json
=> chore: release 1.0.1

example/ios/Podfile.lock, example/src/App.tsx, ios/AdvancedInputMaskDelegateWrapper.swift, ios/AdvancedTextInputMaskDecoratorView.swift
Fixed focus/blur events are not firing on iOS. The problem was related to delegates logic, so, before setting the new delegate we needed to put the previous text field delegate to mask the input listener
onBlur/onFocus must work
**Before**
https://github.com/user-attachments/assets/702c3f86-4bf5-4aa0-a38e-3794111bdc96
**After**
https://github.com/user-attachments/assets/40a33e66-83bc-4568-af39-0694648d8a75
=> fix: focus/blur events don't work on iOS

example/src/App.tsx, src/views/MaskedTextInput/index.tsx
Fixed reference type for MaskedTextInput
ref type must be TextInput
tested via yarn typecheck command
=> fix: ref type

android/src/oldarch/java/com/maskedtextinput/AdvancedTextInputMaskDecoratorViewManagerSpec.kt
With the newest `react-native` version 0.76.5 there is a build error when using `react-native-advanced-input-mask`:
```
> Task :react-native-advanced-input-mask:compileDebugKotlin FAILED
e: file:///Users/mlazari/Desktop/Repos/myapp/node_modules/react-native-advanced-input-mask/android/src/oldarch/java/com/maskedtextinput/AdvancedTextInputMaskDecoratorViewManagerSpec.kt:8:93 Type argument is not within its bounds: should be subtype of 'View'
```
This is likely related to the rewriting of SimpleViewManager from Java to Kotlin in react-native 0.75.0: https://github.com/facebook/react-native/pull/43834/files#diff-23f2d98154bf6cbb23d2c455abe1e70d91962ed0a0460f2cce90adc28b9ddd18R20
This change fixes an Android build error (`Type argument is not within its bounds: should be subtype of 'View'`) …
=> fix: android build error

android/src/main/java/com/maskedtextinput/views/AdvancedTextInputMaskDecoratorView.kt, example/src/App.tsx
If we want to set default value for initial mount it should be done in onAttachedToWindow method. So, I added this and it fixed this problem.
- add set default value call in onAttachedToWindow
Android emulator
https://github.com/user-attachments/assets/b26ea676-8c01-466c-b1c4-5f0829a2ed55
=> fix: default value was not displayed on android on initial mount

WebExample/src/App.tsx, src/web/AdvancedTextInputMaskListener.ts, src/web/hooks/useMaskedTextInputListener/index.ts, src/web/views/MaskedTextInput/index.tsx
Added default value formatting on web
- useMaskedTextInputListener
-
tested via WebExample in chrome browser
https://github.com/user-attachments/assets/f1a73924-b3e0-41e6-b436-0e2705475489
=> feat: add default value formatting on web

.gitignore, android/src/main/java/com/maskedtextinput/views/AdvancedTextInputMaskDecoratorView.kt, example/android/app/src/main/java/com/maskedtextinputexample/MainActivity.kt, example/ios/Podfile.lock, example/package.json, example/src/App.tsx, example/src/navigation/Root/index.tsx, example/src/navigation/Root/types.ts, example/src/navigation/index.tsx, example/src/navigation/screenNames.ts, example/src/screens/Main/index.tsx, example/src/screens/Main/styles.ts, example/src/screens/RNTextInput/index.tsx, example/src/screens/RNTextInput/styles.ts, ios/AdvancedTextInputMaskDecoratorView.swift, ios/AdvancedTextInputViewContainer.h, ios/AdvancedtextInputMaskDecoratorView.mm, yarn.lock
The problem was in AdvancedTextInputMaskDecoratorView. When we navigated from one screen to another we applied a logic to find a new text input component and apply mask logic for it but it is wrong. I added prepareForRecycle method in objective-c method and added cleanup function to remove all strong references. 
I also added navigation to my codebase, so in the future this will help me split the codebase and cover it better with E2E tests.
fixes #44 
- navigation
-
- prepareForRecycle method in AdvancedTextInputMaskDecoratorView(objective-c)
- cleanup method in AdvancedTextInputMaskDecoratorView(swift)
- added handling of initial mount
- added clean up for change text listeners
- added handling of initial mount
Pixel 6a API 35 …
=> fix: advanced text input view is not cleaned up during recycling

WebExample/src/App.tsx, android/src/main/java/com/maskedtextinput/views/AdvancedTextInputMaskDecoratorView.kt, ios/.swiftlint.yml, ios/AdvancedTextInputMaskDecoratorView.swift, ios/NotifyingAdvancedTexInputMaskListener.swift, src/web/AdvancedTextInputMaskListener.ts, src/web/hooks/useMaskedTextInputListener/index.ts, src/web/views/MaskedTextInput/index.tsx
Currently, if you try to dynamically change the allowedKeys parameter, the value of the text is the same as it was before the parameter was updated. I think this is wrong behaviour and we should update the text when we change allowedKeys.
- added ref handling logic
- added reset 
- moved initialization of allowedKeys to constructor method
- added logic for updating text when allowedKeys changed
- added logic for updating text when allowedKeys changed
web(chrome browser)
https://github.com/user-attachments/assets/20e65605-d685-4e2f-9bd7-79de3d7feed4
https://github.com/user-attachments/assets/37d49fe0-9733-4051-9019-53f0aca76868
https://github.com/user-attachments/assets/2ce1144c-ea38-4cf3-8ec1-fcb2775ae978
=> fix: update text value when allowedKeys has been changed

example/src/navigation/Root/index.tsx, example/src/navigation/screenNames.ts, example/src/screens/Date/index.tsx, example/src/screens/Date/styles.ts, example/src/screens/Main/index.tsx, ios/AdvancedTextInputMaskDecoratorView.swift, ios/AdvancedtextInputMaskDecoratorView.mm
I found that during unmounts or re-renders of the text input component, the default value (which is provided from JavaScript) is lost. This issue arises due to the current behavior in the AdvancedTextInputMaskDecoratorView Objective-C file. When the view is being prepared for recycling, we incorrectly reset the view to nil and also reset the delegate, which causes the default value to be lost.
Fix problem with defaultValue on iOS
- added new JS screen Date
-
- fixed default value
- added more logic for clean up
- started using attributed text instead of all text
https://github.com/user-attachments/assets/df5da0d7-6191-424a-b995-762b1bca74d2
https://github.com/user-attachments/assets/0919a85a-ca35-46bd-9043-4e5695d6aed9
=> fix: default value is not set during re-renders/unmount

package/android/src/main/java/com/maskedtextinput/views/AdvancedTextInputMaskDecoratorView.kt
I want to fix the behaviour of the initial value for controlled text inputs, right now it works like this: 
we have defaultValue -> insert it. 
But according to web React rules, defaultValue is only needed for uncontrolled text inputs. So the logic should be like this:
we have a value?
yes, we insert it as defaultValue, 
no, we make a fallback to defaultValue.
Text inputs behavior must be the same across all of the platforms. 
-
-
-
-
- added logic to set default value
-
Android Pixel 6 API 34
https://github.com/user-attachments/assets/d8cd8b72-b963-40ae-923b-f5434c429690
=> fix: initial value for controlled text inputs for android

.github/workflows/build-android-paper.yml
I want to expand my CI and have a paper build of android to ensure my package will work on the old arch as well.
better old arch support
new android-paper-build
tested on CI
=> feat: android paper build on CI

.github/workflows/verify-ios.yml, README.md, apps/example/ios/MaskedTextInputExample/AppDelegate.swift, apps/example/src/navigation/Root/index.tsx, apps/example/src/navigation/screenNames.ts, apps/example/src/screens/Main/constants.ts, apps/example/src/screens/ValidationRegEx/index.tsx, apps/example/src/screens/ValidationRegEx/styles.ts, package/android/src/main/java/com/maskedtextinput/listeners/ReactMaskedTextChangeListener.kt, package/android/src/main/java/com/maskedtextinput/managers/AdvancedTextInputMaskDecoratorViewManager.kt, package/android/src/main/java/com/maskedtextinput/views/AdvancedTextInputMaskDecoratorView.kt, package/android/src/oldarch/java/com/maskedtextinput/AdvancedTextInputMaskDecoratorViewManagerSpec.kt, package/ios/AdvancedTextInputMaskDecoratorView.swift, package/ios/AdvancedTextInputViewContainer.h, package/ios/AdvancedtextInputMaskDecoratorView.mm, package/ios/MaskedTextInputManager.mm, package/ios/NotifyingAdvancedTexInputMaskListener.swift, package/src/native/specs/AdvancedTextInputMaskDecoratorViewNativeComponent.ts, package/src/native/views/MaskedTextInput/index.tsx, package/src/types.ts, package/src/web/AdvancedTextInputMaskListener.ts, package/src/web/hooks/useMaskedTextInputListener/index.ts, package/src/web/views/MaskedTextInput/index.tsx
This world isn't always perfect and sometimes we have to make up new stuff to cover something that doesn't quite make sense. So I introduce a new property: validationRegex, with this property we can do away with allowedKeys completely, because we can validate them via regex, also we can specify the exact position of separators like points.
I want to handle all formatting/allowing/pre-validation logic in one prop
- validationRegex prop
- validationRegex prop
-
- validationRegex prop
-
Chrome browser
https://github.com/user-attachments/assets/264d9332-2777-4e75-b934-4ff9ae32237d
https://github.com/user-attachments/assets/186ad36a-cb03-4d8e-8efc-479fc0ccf063
https://github.com/user-attachments/assets/967dc158-9cac-4c05-82ee-ec5593fbaaa9
=> feat: add validationRegex prop

package/android/src/main/java/com/maskedtextinput/managers/AdvancedTextInputMaskDecoratorViewManager.kt, package/android/src/oldarch/java/com/maskedtextinput/AdvancedTextInputMaskDecoratorViewManagerSpec.kt
I want to fix warnings that are logged during build phase in the android console.
warnings sometimes cause questions for some developers and sometimes it's hard to understand what went wrong
- migrated from MapBuilder to mapOf
- aligned param names with abstract class param names in some methods
- migrated from MapBuilder to mapOf
- aligned param names with abstract class
tested locally and on CI
=> fix: android build warnings

apps/example/src/screens/ValidationRegEx/index.tsx, package/android/src/main/java/com/maskedtextinput/listeners/ReactMaskedTextChangeListener.kt, package/src/web/AdvancedTextInputMaskListener.ts
I had a lot of ideas how do I need to implement it, I thought about `onRegexValidationFailed` prop from the JS side, but my final solution is just to align this logic between platforms. If someone asks me to add an `onRegexValidationFailed` property, I would be happy to do so. However, I don't see any point in it right now.
I want to have one behavior for each platform.
Pixel 6a Emulator
Chrome browser
https://github.com/user-attachments/assets/0723b4ba-83cb-4bdb-91c1-549dfb01f1cb
https://github.com/user-attachments/assets/70e3bf9e-e746-4d87-8cda-35cc8bc2b42c
https://github.com/user-attachments/assets/375113e8-06b9-4758-a7c8-925c101c1294
https://github.com/user-attachments/assets/b3bb7cb3-1085-4662-a7b2-efa0a493187e
=> fix: selection logic on android and web platforms

apps/example/src/screens/Phone/index.tsx, apps/example/src/screens/ValidationRegEx/index.tsx, package/android/src/main/java/com/maskedtextinput/listeners/ReactMaskedTextChangeListener.kt, package/android/src/main/java/com/maskedtextinput/views/AdvancedTextInputMaskDecoratorView.kt, package/ios/AdvancedTextInputMaskDecoratorView.swift, package/ios/NotifyingAdvancedTexInputMaskListener.swift, package/src/web/AdvancedTextInputMaskListener.ts, package/src/web/hooks/useMaskedTextInputListener/index.ts
In this PR, I've added logic to not re-create the regular expression every time the user types, so that should improve performance a bit
better performance
iPhone 15 pro
Chrome browser
https://github.com/user-attachments/assets/de6007f5-3b24-4e81-a181-f65c237e008d
https://github.com/user-attachments/assets/4782b012-c1cb-4549-a45f-09f8c9b53a48
https://github.com/user-attachments/assets/fb94e5ae-cfb0-4e63-98f9-5385e2bbc299
=> fix: dont create validation regex every time when user changes text

package/src/web/AdvancedTextInputMaskListener.ts, package/src/web/hooks/useMaskedTextInputListener/index.ts
When you have a default value and you try to enter some forbidden character with validationRegex prop, the field becomes empty. This is because the afterText value is empty, and it reverts to that value if the validation regex is not passed. So, I added a proper logic to handle this case and it fixed the problem.
text input should not become empty if you enter any forbidden characters.
- handling of default value in MaskedTextChangedListener class
tested on the Web browser
https://github.com/user-attachments/assets/8fd9cdd6-e698-4925-b04f-a10aa968aa4a
https://github.com/user-attachments/assets/53e5049b-4a25-4fcc-ad0c-9bd22bd33116
=> fix: field becomes empty after entering forbidden character

package/ios/AdvancedTextInputMaskDecoratorView.swift
The problem was in the willMoveToWindow function. This method is called too early, and the superview might be nil. I moved all the logic from willMoveToWindow to didMoveToWindow, which fixed the problem.
fixes #77 
Masked text input should be configured correctly
- replaced willMoveToWindow with didMoveToWindow
https://github.com/user-attachments/assets/57290c16-8b0d-4166-a451-359554e07404
https://github.com/user-attachments/assets/492343cb-4278-49af-bd1c-537f71378fab
https://github.com/user-attachments/assets/f6bd5ae8-950e-47aa-8d3b-e34385d3c3c7
=> fix: configure text field when view moved to window

README.md, apps/example/src/components/TextInput/index.tsx, package/android/src/main/java/com/maskedtextinput/views/AdvancedTextInputMaskDecoratorView.kt, package/ios/AdvancedTextInputMaskDecoratorView.swift, package/src/web/AdvancedTextInputMaskListener.ts
I want to set autocomplete as true by default as it was before to avoid breaking changes for people who use my library.
Don't bring breaking changes
iPhone 15 pro
Chrome
https://github.com/user-attachments/assets/f2a38757-99f9-4700-842f-4ddb1de69ec0
https://github.com/user-attachments/assets/aae2d47b-adca-4506-ba53-49c2dbe6c6e0
https://github.com/user-attachments/assets/bc81c4b5-47fe-4e41-a868-dfbca38f64ca
=> fix: revert autocomplete is false by default

apps/example/src/screens/ControlledInput/index.tsx, package/android/src/main/java/com/maskedtextinput/listeners/ReactMaskedTextChangeListener.kt, package/android/src/main/java/com/maskedtextinput/views/AdvancedTextInputMaskDecoratorView.kt
I don't know why, but react-native sets the text multiple times. To avoid applying the mask multiple times, I added logic to compare the previously entered value with the next value and added setting the initial value after applying the initial value
Do not apply the mask if the text has not been modified
https://github.com/user-attachments/assets/516b07d4-872c-41ee-8049-f66b4cde0b5a
https://github.com/user-attachments/assets/c4c6c684-1c09-46af-8077-760852d9918b
=> fix: android initial value with autocomplete=true

package/ios/AdvancedTextInputMaskDecoratorView.swift
The problem is that for unknown reason we get value for uncontrolled text inputs as empty String, however the initial value is nil. It happens when you enter the controlled text input example.
- getInitialText util
iPhone 15 pro
https://github.com/user-attachments/assets/f1622f36-e767-4511-b85b-29281c363c78
https://github.com/user-attachments/assets/14a8294f-741c-44bb-946d-408c055dbe5e
=> fix: properly set initial value on iOS

package/ios/MaskedTextInputManager.mm
I forgot to add this prop for the old arch for iOS. So, I aded it and it fixed crash.
fixes: #97 
We should support all props for all archs
- added RCT_EXPORT_VIEW_PROPERTY(affinityFormat, NSArray)
tested on iPhon 15pro iOS 17.5
https://github.com/user-attachments/assets/225d4610-74e8-4ec0-8a3c-9b56f4162bdc
=> fix: add affineFormat for iOS old arch

package/android/src/main/java/com/maskedtextinput/managers/AdvancedTextInputMaskDecoratorViewManager.kt
In terms to support older versions of react-native we need to use MapBuilder. So, I returned it in the codebase.
fixes #100 
Support for older versions is also important!
- MapBuilder instead of mapOf
-
Android emulator
old arch:
https://github.com/user-attachments/assets/e1706ff8-dcb8-447b-b929-44234770a6ce
new arch:
https://github.com/user-attachments/assets/c5976e21-ff12-4b4a-8150-bb5cd5996efd
=> fix: return MapBuilder

apps/example/src/components/TextInput/index.tsx, e2e/.maestro/clear-text.yaml, e2e/.maestro/set-text.yaml, package/android/src/main/java/com/maskedtextinput/managers/AdvancedTextInputMaskDecoratorViewManager.kt, package/android/src/main/java/com/maskedtextinput/views/AdvancedTextInputMaskDecoratorView.kt, package/android/src/oldarch/java/com/maskedtextinput/AdvancedTextInputMaskDecoratorViewManagerSpec.kt, package/ios/AdvancedTextInputMaskDecoratorView.swift, package/ios/AdvancedTextInputMaskDecoratorViewManager.swift, package/ios/AdvancedTextInputViewContainer.h, package/ios/AdvancedtextInputMaskDecoratorView.mm, package/ios/MaskedTextInput-Bridging-Header.h, package/ios/MaskedTextInputManager.mm, package/src/native/MaskedTextInputNative.tsx, package/src/native/specs/AdvancedTextInputMaskDecoratorViewNativeComponent.ts, package/src/native/views/MaskedTextInput/index.tsx, package/src/types.ts
It looks like when we call `clear` method from react-native it doesn't notify text listeners about it on the native side. So, I decided to implement our own methods to control it.
It solves a problem with the correct updating of dispatched text
- added two methods setText(text: string, autocomplete: boolean) and clear
- added setText native command
- added setText native command
https://github.com/user-attachments/assets/4e808b65-d05d-4180-852a-21da4c2408fa
https://github.com/user-attachments/assets/c8dd24f6-fc12-48cf-aa41-40c8e711e88b
https://github.com/user-attachments/assets/427f939f-2648-4f4e-9fb0-44e036c15604
https://github.com/user-attachments/assets/f97966f5-a190-4732-9a12-655ad45353f2
=> feat: add setText native command

package/ios/AdvancedTextInputMaskDecoratorView.swift
I added this logic to be consistent with android platfrom which dispatches these event twice. However, iOS works well without this and we can remove this check.
- remove check for the previous dispatched event
-
iPhone 16 pro simulator
Fabric:
https://github.com/user-attachments/assets/ae805af6-feb1-45be-aa8b-3ab976e92d3a
Old:
https://github.com/user-attachments/assets/df86444b-c6bd-4313-b81d-11665799618f
Fabric:
https://github.com/user-attachments/assets/e592cb3b-6f0a-411c-beb3-5e0e7e9c6eb6
Old:
https://github.com/user-attachments/assets/e46eac6d-9702-4083-9b0a-ca91619aecfe
=> fix: remove verification of a previously sent event on iOS

package/src/index.tsx
Export `MaskedTextInputRef` alongside `MaskedTextInputProps`.
Allows proper typing when using `useRef` with `MaskedTextInput`, e.g.:
`const inputWithMaskRef = useRef<MaskedTextInputRef>(null);`
- Exported `MaskedTextInputRef` type from the module, same as `MaskedTextInputProps`.
-
-
- Confirmed the type is correctly exported and usable in an external project.
- No runtime changes; type-only update.
=> feat: add MaskedTextInputRef to export

.github/workflows/ios-e2e-test.yml, apps/example/ios/Podfile.lock, apps/example/package.json, package/android/src/main/java/com/maskedtextinput/views/AdvancedTextInputMaskDecoratorView.kt, package/ios/AdvancedTextInputMaskDecoratorView.swift, package/src/native/views/MaskedTextInput/index.tsx
In this PR, I moved the decorator view before the TextInput component to fix a problem with setting the delegate.
react-native-keyboard-controller sets its own delegate, and after hiding the keyboard, it resets the delegate to the initial value. Since my delegate was set after react-native-keyboard-controller's it cleans up and mask doesn't work.
fixes #128
- moved decorator view before text input
iPhone 16 pro simulator
Pixel 3a emulator
https://github.com/user-attachments/assets/537224d7-1376-474d-89e9-d73d257edf52
https://github.com/user-attachments/assets/092c0a3f-def5-4730-9ed0-62b9ff3b198c
https://github.com/user-attachments/assets/ff47fe8d-a785-41bc-add7-c7ea0930cddf
https://github.com/user-attachments/assets/19959951-fbda-43a9-9512-856435cd1f97
=> fix: keyboard controller with autofocus

package/android/src/main/java/com/maskedtextinput/views/AdvancedTextInputMaskDecoratorView.kt
Added a flag isSettingFromJS in AdvancedTextInputMaskDecoratorView to distinguish between text updates coming from JavaScript props (value) and user input. This prevents dispatching onChangeText events when the text is programmatically updated from JS.
Previously, updating the text via the value prop from JavaScript would trigger onChangeText events in native code, causing unnecessary re-renders and potential loops in React Native. This change ensures that only user-initiated input triggers events, improving performance and correctness.
- No changes in JS API, behavior remains the same.
- No changes.
- Added isSettingFromJS flag in AdvancedTextInputMaskDecoratorView.
- Modified valueListener to skip dispatching ChangeTextEvent when isSettingFromJS is true.
- Updated setValue and setText …
=> feat(android): prevent onChangeText when updating value from JS
