IvanIhnatsiuk/react-native-advanced-input-mask

- src/index.tsx
- src/types.ts
This pull request includes changes to the `MaskedTextInput` component to simplify types and improve the codebase. The most important changes include modifying type imports and adjusting type definitions.
> fix: Remove unused types

- example/ios/Podfile.lock
- example/src/App.tsx
- ios/MaskedTextInput.swift
Fixed controlled text input behavior on iOS devices.
https://github.com/user-attachments/assets/e0a9d8d0-19e4-48bd-b37c-a9a152e85245
https://github.com/user-attachments/assets/bdaefff2-7787-45fe-a74c-ecba511c33d4
> fix: controlled text input on iOS

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Added GitHub templates to improve pull request creation and bug reporting experience.
> feat: add github templates

- .github/workflows/verify-android.yml
> feat: add ktlint

- jest/index.js
Added jest mock setup to simplify dev work with unit tests.
> feat: add jest mocks

- .github/workflows/build-ios.yml
- .gitignore
- android/src/newarch/java/com/maskedtextinput/AdvancedTextInputMaskDecoratorViewManagerSpec.kt
- example/Gemfile
- example/android/app/build.gradle
- example/android/app/src/main/AndroidManifest.xml
- example/android/app/src/main/java/com/maskedtextinputexample/MainApplication.kt
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
- example/android/gradlew
- example/android/gradlew.bat
- example/android/settings.gradle
- example/ios/MaskedTextInputExample.xcodeproj/project.pbxproj
- example/ios/MaskedTextInputExample/AppDelegate.mm
- example/ios/MaskedTextInputExample/Info.plist
- example/ios/Podfile
- example/ios/Podfile.lock
- example/package.json
- package.json
- yarn.lock
As a developer, I want to support the latest version of react-native.
Android emulator
https://github.com/user-attachments/assets/e4a78619-ae85-467b-9c26-21e902b2f7ce
https://github.com/user-attachments/assets/84e0c219-99f7-46e5-8dc9-68c4561aca84
> chore: react-native 0.76

- .github/workflows/build-ios.yml
Added ccache support for CI to reduce build time.
> feat: setup ccache for CI

- example/ios/Podfile.lock
- package.json
> chore: release 1.1.1

- ios/AdvancedTextInputMaskDecoratorView.swift
just simplified and did a little cleanup in the AdvancedTextInputMaskDecoratorView class
Code should be clean and easy readable
Tested fabric and paper on iOS
> fix: re-format swift code

- .github/workflows/build-ios-paper.yml
Added paper iOS build on CI to be sure that this library works on paper react-native arch
tested on CI
> feat: add paper ios build on CI

- example/ios/Podfile.lock
- package.json
> chore: release: release 1.1.3

- README.md
I have updated the readme file to include the autocomplete={false} property and remove the unnecessary View element
It would be easier for people to use this library with clear and clean examples
Updated Readme.MD
> fix: update readme file

- example/ios/Podfile.lock
- package.json
> chore: release v1.2.0

- example/ios/Podfile.lock
- package.json
> chore: release v1.2.1

- .github/workflows/publish.yml
Added "verified" badge near to package version to npm registry. 
Such badge gives more confidence to users that such package is official etc.
Than more confidence in package quality people have, than more they like the pacakge and in the end it will gain the popularity of the pacakge 👀
add provenance flag to npm publish command;
Can be tested only when new release gets published 🤷‍♂️
> feat: add publish job

- example/ios/Podfile.lock
- package.json
> chore: release v1.2.2

- .github/workflows/build-web.yml
Added a build-web task that provides better stability for the web.
more stability, better life
tested on CI
> feat: add build-web job

- .github/workflows/publish.yml
- package/package.json
Added readme and license files for npm package
I want to have these files in NPM
impossible to test right now 🙁
> fix: add readme and license file for npm package

- apps/example/ios/Podfile.lock
- package/package.json
> chore: release 1.2.3

- apps/example/ios/Podfile.lock
- package/package.json
> chore: release v1.3.0

- apps/example/ios/Podfile.lock
- package/package.json
> chore: release v1.3.1

- .github/workflows/android-e2e-test.yml
- .github/workflows/ios-e2e-test.yml
I want to *always* upload the e2e test report to better understand what went wrong if the test fails
Better debugging 
Tested on CI
> fix: always upload test reports

- apps/example/ios/Podfile.lock
- package/package.json
> chore: release v1.3.2

- package/android/src/main/java/com/maskedtextinput/listeners/ReactMaskedTextChangeListener.kt
- package/ios/NotifyingAdvancedTexInputMaskListener.swift
We don't need to apply default values for constructors because we already have all of these values in manager classes.
Remove unused code
iPhone 15 pro
https://github.com/user-attachments/assets/cca411fa-067b-4b1c-895d-fbc09c60aec4
https://github.com/user-attachments/assets/d1c69029-219f-4887-a128-4b4b2176456e
> fix: remove default values from native code

- apps/example/ios/Podfile.lock
- package/package.json
> chore: release v1.3.3

- apps/example/src/screens/ControlledInput/index.tsx
- e2e/.maestro/controlled-input.yaml
Added e2e test for controlled input
Recently I have some bugs for controlled text input component and I avoid them in the future.
Added controolled-input.yml
tested locally on Android emulator and iOS simulator
https://github.com/user-attachments/assets/7b1dcb91-a933-4afa-bdbf-44c6f060f840
https://github.com/user-attachments/assets/79c43814-c2e2-461d-9c6f-c0fedd5d6708
> feat: add controlled input e2e test

- apps/example/ios/Podfile.lock
- package/package.json
> chore: release v1.3.4

- apps/example/ios/Podfile.lock
- package/package.json
> chore: release v1.3.5

- apps/example/babel.config.js
- apps/example/package.json
- yarn.lock
I want to follow best practices in my sample application. So I decided to install react-compiler 🙂 . 
React best practices
- added babel-plugin-react-compiler
android emulator
Web browser
Android:
https://github.com/user-attachments/assets/1db3bb96-ae0d-4d24-91f9-a80f53f6f9e4
Web:
https://github.com/user-attachments/assets/b77ff3ab-0001-4783-81e6-0dc61205f748
> feat: setup react-compiler

- package/ios/AdvancedTextInputMaskDecoratorView.swift
Currently we don't update the value when we changed mask prop if value is the same as we already have in `UITextField`. However, this approach is wrong because we need to compare it with masked value.
fixes #108 
value must always be synchronized with the mask
- properly update value after mask changing
- new getMaskResultForText util
https://github.com/user-attachments/assets/e2712844-9e70-44fc-bf46-4583cabbea42
https://github.com/user-attachments/assets/98caeaec-5d5b-4ee0-8e88-4a8c09f5a1f5
> fix: update value if mask changed

- apps/example/ios/Podfile.lock
- package/package.json
> chore: release v1.3.6

- apps/example/ios/Podfile.lock
- package/package.json
> chore: release v1.4.0

- apps/example/ios/Podfile.lock
- package/package.json
> chore: release v1.4.1

- apps/example/ios/Podfile.lock
- package/package.json
> chore: release v1.4.3

- apps/example/ios/Podfile.lock
- package/package.json
> release: v1.4.5
